version: '3'

services:
  backend:
    build: .
    command: /app/node_modules/.bin/nodemon ./index.js
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/app
      - ./node_modules:/app/node_modules
